print("ingrese las notas del estudiante")
N1 = float(input("ingrese la nota 1:"))
N2 = float(input("ingrese la nota 2:"))
N3 = float(input("ingrese la nota 3:"))
P = float(N1+N2+N3/3)
print("las nota promedio del alumno es: " )
print(P)