print("cuantos partidos gano ABC club?")
G=int(input())
print("cuantos partidos perdio ABC club?")
P=int(input())
print("cuantos partidos empato ABC club?")
E=int(input())
R=int((G*3)+(E))
print("el puntaje total de ABC club es de:")
print(R)