print("ingrese la coordenada X de A")
AX=float(input())
print("ingrese la coordenada Y de A")
AY=float(input())
print("ingrese la coordenada X de B")
BX=float(input())
print("ingrese la coordenada Y de B")
BY=float(input())
D=float(((AX-BX)**2 +(AY-BY)**2)**0.5)
print(D)